### PR TITLE
Bookstore: initialize project with components

### PR DESCRIPTION
**Pull request by Elhambasir**
### Bookstore: initialize the project with components.

- [x] Used React Router.
- [x] Used React components.

Added 2 routes in the application, to render a page component:

`/`
`/categories
`

- [x] Created components inside of the /components directory:

### How should it be tested?

**Clone the repository**
```javascript
git clone https://github.com/Elhambasir/bookstore.git
``` 

**Navigate to the folder**
```javascript
 cd bookstore
``` 

**Checkout the branch**
```javascript
 git checkout bookstor-initializer
``` 

**Finally run this:**
```javascript
 npm start
``` 

**For testing run this:**
```javascript
npm run test
``` 

### If you face this error : _['react-scripts' is not recognized as an internal or external command]_

_Please run this command:_
```javascript
npm install react-scripts --save-dev
```

### CODE REVIEW

**Review by GedeonTS — COMMENTED** [review]
# INVALID REVIEW REQUEST

Hi @Elhambasir , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the Linters set up. Kindly make sure to set up the Linters and have them running with no errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Elhambasir** [comment]
Ok thank you I fixed that.

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢 🟢 🟢 

Hi @Elhambasir,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Initialized project with create-react-app and react-router-dom 👍🏽
✅ Set up components correctly as expected 👍🏽
✅ The app runs fine 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Elhambasir** [comment]
Thank you

**Pull request merged**
